CREATE TABLE `IMOBILIARIA`.`SITUACAO_IMOVEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SITUACAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;

INSERT INTO SITUACAO_IMOVEL(SITUACAO) VALUES ('ALUGADO');
INSERT INTO SITUACAO_IMOVEL(SITUACAO) VALUES ('LIVRE');

CREATE TABLE `IMOBILIARIA`.`PROPRIETARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `EMAIL` VARCHAR(120) NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;

CREATE TABLE `IMOBILIARIA`.`IMOVEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENDERECO` VARCHAR(120) NOT NULL,
  `BAIRRO` VARCHAR(120) NOT NULL,
  `CIDADE` VARCHAR(120) NOT NULL,
  `PAIS` VARCHAR(120) NOT NULL,
  `PRECO` DOUBLE NOT NULL,
  `OWNER` VARCHAR(45) NULL,
  `ID_SITUACAO` INT NOT NULL,
  `ID_PROPRIETARIO` INT NULL,
  `FL_FINANCIADO` CHAR(1) NULL,
  `FL_PROPRIETARIO` CHAR(1) NULL,
  `FL_NEGOCIACAO` CHAR(1) NULL,
  `DT_CADASTRO` DATE NULL,
  `DT_ALTERACAO` DATE NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_SITUACAO_IDX` (`ID_SITUACAO` ASC),
  INDEX `PROPRIETARIO_IDX` (`ID_PROPRIETARIO` ASC),
  CONSTRAINT `IMOVEL_SITUACAO`
    FOREIGN KEY (`ID_SITUACAO`)
    REFERENCES `IMOBILIARIA`.`SITUACAO_IMOVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROPRIETARIO`
    FOREIGN KEY (`ID_PROPRIETARIO`)
    REFERENCES `IMOBILIARIA`.`PROPRIETARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF32;
