CREATE SCHEMA `usuarios` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `usuarios`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(4000) NOT NULL,
  `st_ativo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `usuarios`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

insert into role(nome) values ('ADMIN');
insert into role(nome) values ('APROVADOR');
insert into role(nome) values ('CADASTRADOR');

CREATE TABLE `usuarios`.`user_role` (
  `id_user` INT NOT NULL,
  `id_role` INT NOT NULL,
  INDEX `id_user_idx` (`id_user` ASC),
  INDEX `id_role_idx` (`id_role` ASC),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `usuarios`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `usuarios`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

////////////////////////////////////////////////////////////////////////////////

CREATE SCHEMA `imobiliaria` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `IMOBILIARIA`.`SITUACAO_IMOVEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SITUACAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;

INSERT INTO SITUACAO_IMOVEL(SITUACAO) VALUES ('ALUGADO');
INSERT INTO SITUACAO_IMOVEL(SITUACAO) VALUES ('LIVRE');

CREATE TABLE `IMOBILIARIA`.`PROPRIETARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(120) NOT NULL,
  `EMAIL` VARCHAR(120) NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8;

CREATE TABLE `IMOBILIARIA`.`IMOVEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENDERECO` VARCHAR(120) NOT NULL,
  `BAIRRO` VARCHAR(120) NOT NULL,
  `CIDADE` VARCHAR(120) NOT NULL,
  `PAIS` VARCHAR(120) NOT NULL,
  `PRECO` DOUBLE NOT NULL,
  `OWNER` VARCHAR(45) NULL,
  `ID_SITUACAO` INT NOT NULL,
  `ID_PROPRIETARIO` INT NULL,
  `FL_FINANCIADO` CHAR(1) NULL,
  `FL_PROPRIETARIO` CHAR(1) NULL,
  `FL_NEGOCIACAO` CHAR(1) NULL,
  `DT_CADASTRO` DATETIME NULL,
  `DT_ALTERACAO` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_SITUACAO_IDX` (`ID_SITUACAO` ASC),
  INDEX `PROPRIETARIO_IDX` (`ID_PROPRIETARIO` ASC),
  CONSTRAINT `IMOVEL_SITUACAO`
    FOREIGN KEY (`ID_SITUACAO`)
    REFERENCES `IMOBILIARIA`.`SITUACAO_IMOVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROPRIETARIO`
    FOREIGN KEY (`ID_PROPRIETARIO`)
    REFERENCES `IMOBILIARIA`.`PROPRIETARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF32;

CREATE TABLE `imobiliaria`.`imagem_imovel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_imovel` INT NOT NULL,
  `blob_imagem` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `imovel_idx` (`id_imovel` ASC),
  CONSTRAINT `imovel`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `imobiliaria`.`imovel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
