import React, { useEffect, useState } from "react";
import DynamicTable from "../components/GenericComponents/DynamicTable";
import { getAuditoria, editOwner, postOwner } from "../services/ImobiliariaService";
import { useDispatch, useSelector } from "react-redux";
import * as DynamicTableActions from "../redux/actions/DynamicTableActions";
import { QuickSort } from "../services/General";

const data = [
	{
		"id" : 1,
		"rev" : 2,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 2,
		"rev" : 3,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 2,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 3,
		"rev" : 4,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 3,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 4,
		"rev" : 5,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 4,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 5,
		"rev" : 6,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 6,
		"rev" : 7,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 7,
		"rev" : 8,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 8,
		"rev" : 9,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 9,
		"rev" : 10,
		"revtype" : 0,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "Rua Teste 1234",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 255555555,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 10,
		"rev" : 11,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 11,
		"rev" : 12,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 12,
		"rev" : 13,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 13,
		"rev" : 14,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 14,
		"rev" : 15,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 15,
		"rev" : 17,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 16,
		"rev" : 18,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 17,
		"rev" : 19,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 18,
		"rev" : 20,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 19,
		"rev" : 21,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 20,
		"rev" : 22,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 21,
		"rev" : 23,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 22,
		"rev" : 24,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 23,
		"rev" : 25,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 24,
		"rev" : 26,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 25,
		"rev" : 27,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 26,
		"rev" : 28,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 27,
		"rev" : 29,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 28,
		"rev" : 30,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 29,
		"rev" : 31,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 30,
		"rev" : 32,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 31,
		"rev" : 34,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 32,
		"rev" : 36,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 33,
		"rev" : 38,
		"revtype" : 0,
		"bairro" : "Timbaúva",
		"cidade" : "Montenegro",
		"endereco" : "Rua Palmeira, 45",
		"fl_financiado" : "N",
		"fl_negociacao" : "N",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "Brasil",
		"preco" : 1500000,
		"id_proprietario" : 1,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 34,
		"rev" : 39,
		"revtype" : 0,
		"bairro" : "a",
		"cidade" : "a",
		"endereco" : "a",
		"fl_financiado" : "N",
		"fl_negociacao" : "N",
		"fl_proprietario" : "S",
		"owner" : "a",
		"pais" : "a",
		"preco" : 1500000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 35,
		"rev" : 41,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 36,
		"rev" : 42,
		"revtype" : 0,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 34,
		"rev" : 43,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 32,
		"rev" : 44,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "aavbaba",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 9,
		"rev" : 45,
		"revtype" : 1,
		"bairro" : "Bairro Teste 1234",
		"cidade" : "Cidade Teste 1234",
		"endereco" : "abababccc",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "Paulo Pires de Avila",
		"pais" : "País teste 1234",
		"preco" : 150007,
		"id_proprietario" : 1,
		"id_situacao" : 1,
		"operador" : null
	},
	{
		"id" : 30,
		"rev" : 46,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "abababccc",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 31,
		"rev" : 47,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "ababaccc",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 31,
		"rev" : 48,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 199999,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 26,
		"rev" : 49,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Aalves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 32,
		"rev" : 50,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "aavbaba",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "321",
		"pais" : "Brasil",
		"preco" : 199000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 34,
		"rev" : 51,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartzaaa",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "paulopiresavila@gmail.com",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 34,
		"rev" : 52,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartz",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "paulopiresavila@gmail.com",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 34,
		"rev" : 53,
		"revtype" : 1,
		"bairro" : "Bela Vista",
		"cidade" : "Nova Hartzaa",
		"endereco" : "Protásio Alves, 155",
		"fl_financiado" : "S",
		"fl_negociacao" : "S",
		"fl_proprietario" : "S",
		"owner" : "paulopiresavila@gmail.com",
		"pais" : "Brasil",
		"preco" : 150000,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 37,
		"rev" : 82,
		"revtype" : 0,
		"bairro" : "dsaasd",
		"cidade" : "dsadsa",
		"endereco" : "asdasd",
		"fl_financiado" : "S",
		"fl_negociacao" : "N",
		"fl_proprietario" : "S",
		"owner" : "paulopiresavila@gmail.com",
		"pais" : "abttbt",
		"preco" : 666666666,
		"id_proprietario" : 5,
		"id_situacao" : 3,
		"operador" : null
	},
	{
		"id" : 38,
		"rev" : 84,
		"revtype" : 0,
		"bairro" : "ccccc",
		"cidade" : "sssss",
		"endereco" : "bbbbb",
		"fl_financiado" : "S",
		"fl_negociacao" : "N",
		"fl_proprietario" : "S",
		"owner" : "312",
		"pais" : "eeeee",
		"preco" : 555555555555,
		"id_proprietario" : 5,
		"id_situacao" : 2,
		"operador" : null
	},
	{
		"id" : 38,
		"rev" : 86,
		"revtype" : 1,
		"bairro" : "cccee",
		"cidade" : "ssssass",
		"endereco" : "bbbcc",
		"fl_financiado" : "S",
		"fl_negociacao" : "N",
		"fl_proprietario" : "S",
		"owner" : "312",
		"pais" : "eeeeeasv",
		"preco" : 555555555555,
		"id_proprietario" : 3,
		"id_situacao" : 1,
		"operador" : null
	}
];

const Auditoria = () => {
    const dispatch = useDispatch();
    const [owners, setOwners] = useState(null);
    const userSelector = useSelector((state) => state.UserReducer);
    const [refresh, setRefresh] = useState(false);

    const handleEdit = (updatedOwners) => {
        if (userSelector.token || localStorage.getItem("userCredentials")) {
            updatedOwners.forEach((updatedOwner) => {
                editOwner(
                    updatedOwner,
                    userSelector.token ||
                    JSON.parse(localStorage.getItem("userCredentials")).access_token
                )
            })
        }
    }
    const handleAdd = (newOwner) => {
        if (userSelector.token || localStorage.getItem("userCredentials")) {
            postOwner(
                newOwner,
                userSelector.token ||
                JSON.parse(localStorage.getItem("userCredentials")).access_token
            ).then(() => setRefresh(true));
        }
    }
    useEffect(() => {
        if (userSelector.token || localStorage.getItem("userCredentials")) {
            getAuditoria(
                new URLSearchParams(window.location.search).get("id"),
                userSelector.token ||
                JSON.parse(localStorage.getItem("userCredentials")).access_token
            ).then((resp) => {
                if (resp)
                    setOwners(QuickSort(resp, 0, resp.length - 1, "id", "asc"));
            });
        }
    }, [])

    useEffect(() => {
        if (refresh && (userSelector.token || localStorage.getItem("userCredentials"))) {
            getAuditoria(
                new URLSearchParams(window.location.search).get("id"),
                userSelector.token ||
                JSON.parse(localStorage.getItem("userCredentials")).access_token
            ).then((resp) => {
                if (resp) {
                    dispatch(DynamicTableActions.SetInitialData(resp))
                    setOwners(resp);
                }
            });
            setRefresh(false)
        }
    }, [refresh])

    return (
        <div className="navbarSpace">
            {owners &&
                <DynamicTable
                    title="Auditoria"
                    data={data} />
            }
        </div>
    );
};
export default Auditoria;