export const PUSH_TOASTER = "PUSH_TOASTER";
export const POP_TOASTER = "POP_TOASTER"; 
export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const POP_NOTIFICATION = "POP_NOTIFICATION";
export const SET_FILTERS = "SET_FILTER_WITH_PHOTOS";